export const WISHLIST_ADD_ITEM = "WISHLIST_ADD_ITEM";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
export const WISHLIST_EMPTY = "WISHLIST_EMPTY";

export const SET_DISCOUNT = "SET_DISCOUNT";
export const RESET_DISCOUNT = "RESET_DISCOUNT";
