const data = {
	products: [
		{
			_id: "1",
			name: "Wireless charging stand",
			category: "Charging",
			image: "/images/p1.jpg",
			price: 29,
			countInStock: 10,
			brand: "Anker",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "2",
			name: "Smart wallet",
			category: "Accessories",
			image: "/images/p2.jpg",
			price: 10,
			countInStock: 20,
			brand: "Ekster",
			rating: 3.0,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "3",
			name: "Soundcore liberty pro 2",
			category: "Headphones",
			image: "/images/p3.jpg",
			price: 149,
			countInStock: 0,
			brand: "Anker",
			rating: 4.8,
			numReviews: 17,
			description: "high quality product",
		},
		{
			_id: "4",
			name: "Apple airpods pro",
			category: "Headphones",
			image: "/images/p4.jpg",
			price: 249,
			countInStock: 15,
			brand: "Apple",
			rating: 4.5,
			numReviews: 14,
			description: "high quality product",
		},
		{
			_id: "5",
			name: "Apple iPad",
			category: "Tablet",
			image: "/images/p5.jpg",
			price: 329,
			countInStock: 5,
			brand: "Apple",
			rating: 4.5,
			numReviews: 10,
			description: "high quality product",
		},
		{
			_id: "6",
			name: "WD Portable SSD (500GB)",
			category: "Storage",
			image: "/images/p6.jpg",
			price: 119,
			countInStock: 12,
			brand: "WD",
			rating: 4.5,
			numReviews: 15,
			description: "high quality product",
		},
	],
};
export default data;
